server:
  port: 4550

management:
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, prometheus

springdoc:
  packagesToScan: uk.gov.hmcts.reform.civil.controllers
  writer-with-order-by-keys: true

spring:
  aop:
    proxy-target-class: false
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  config:
    import: "optional:configtree:/mnt/secrets/civil-rtl-export/"
  application:
    name: Civil Judgement Feed
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${JF_DB_HOST:localhost}:${JF_DB_PORT:5432}/${JF_DB_NAME:civil_rtl_export}${JF_DB_OPTIONS:}
    username: ${JF_DB_USERNAME:jf_user}
    password: ${JF_DB_PASSWORD:jf_pass}
    hikari:
      minimumIdle: ${JF_DB_MIN_IDLE:2}
      maximumPoolSize: ${JF_DB_MAX_POOL_SIZE:8}
      idleTimeout: ${JF_DB_IDLE_TIMEOUT:300000}
      maxLifetime: ${JF_DB_MAX_LIFTIME:7200000}
      connectionTimeout: 60000
  jpa:
    open-in-view: false
    database: postgresql
    properties:
      hibernate:
        order_inserts: true
        order_updates: true
        jdbc:
          batch_versioned_data: true
          batch_size: 100
        temp:
          use_jdbc_metadata_defaults: false
  flyway:
    ignore-missing-migrations: 'true'
    baseline-version: '0001'
    out-of-order: 'true'
    baseline-on-migrate: 'true'

feign:
  circuitbreaker:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: BASIC
      postFeignClient:
        loggerLevel: FULL
#idam:
#  s2s-authorised:
#    services: ${CIVIL_SDT_S2S_AUTHORISED_SERVICES:civil_sdt}
#  s2s-auth:
#    microservice: civil_sdt
#    totp_secret: ${CIVIL_SDT_S2S_KEY:AAAAAAAAAAAAAAAA}
#    url: ${IDAM_S2S_URL:http://localhost:4502}
#  sdt:
#    username: ${IDAM_SDT_USERNAME:master.sdt@gmail.com}
#    password: ${IDAM_SDT_PASSWORD:Pa55word11}
#  api:
#    url: ${IDAM_API_URL:http://localhost:5000}
#  client:
#    id: civil_sdt
#    secret: ${IDAM_SDT_CLIENT_SECRET:civil_sdt_secret}
#    scope: openid profile roles
#    # The redirect_uri property is not used by SDT.  Included as required by IDAM for token generation.
#    redirect_uri: http://civil-sdt/oauth2redirect
#civil:
#  api:
#    url: ${CIVIL_API_URL:http://localhost:5000}

rtl-export:
  validate:
    service-ids[0]: "AAA3"
    service-ids[1]: "AAA6"
    service-ids[2]: "AAA7"
  replace:
    character-replacements:
      - charValue: 192
        description: "Latin capital letter A with grave"
        replacement: "A"
      - charValue: 193
        description: "Latin capital letter A with acute"
        replacement: "A"
      - charValue: 194
        description: "Latin capital letter A with circumflex"
        replacement: "A"
      - charValue: 196
        description: "Latin capital letter A with dieresis"
        replacement: "A"
      - charValue: 200
        description: "Latin capital letter E with grave"
        replacement: "E"
      - charValue: 201
        description: "Latin capital letter E with acute"
        replacement: "E"
      - charValue: 202
        description: "Latin capital letter E with circumflex"
        replacement: "E"
      - charValue: 203
        description: "Latin capital letter E with dieresis"
        replacement: "E"
      - charValue: 204
        description: "Latin capital letter I with grave"
        replacement: "I"
      - charValue: 205
        description: "Latin capital letter I with acute"
        replacement: "I"
      - charValue: 206
        description: "Latin capital letter I with circumflex"
        replacement: "I"
      - charValue: 207
        description: "Latin capital letter I with dieresis"
        replacement: "I"
      - charValue: 210
        description: "Latin capital letter O with grave"
        replacement: "O"
      - charValue: 211
        description: "Latin capital letter O with acute"
        replacement: "O"
      - charValue: 212
        description: "Latin capital letter O with circumflex"
        replacement: "O"
      - charValue: 214
        description: "Latin capital letter O with dieresis"
        replacement: "O"
      - charValue: 217
        description: "Latin capital letter U with grave"
        replacement: "U"
      - charValue: 218
        description: "Latin capital letter U with acute"
        replacement: "U"
      - charValue: 219
        description: "Latin capital letter U with circumflex"
        replacement: "U"
      - charValue: 220
        description: "Latin capital letter U with dieresis"
        replacement: "U"
      - charValue: 7808
        description: "Latin capital letter W with grave"
        replacement: "W"
      - charValue: 7810
        description: "Latin capital letter W with acute"
        replacement: "W"
      - charValue: 372
        description: "Latin capital letter W with circumflex"
        replacement: "W"
      - charValue: 7812
        description: "Latin capital letter W with dieresis"
        replacement: "W"
      - charValue: 7922
        description: "Latin capital letter Y with grave"
        replacement: "Y"
      - charValue: 221
        description: "Latin capital letter Y with acute"
        replacement: "Y"
      - charValue: 374
        description: "Latin capital letter Y with circumflex"
        replacement: "Y"
      - charValue: 376
        description: "Latin capital letter Y with dieresis"
        replacement: "Y"
      - charValue: 198
        description: "Latin capital letter AE"
        replacement: "AE"
      - charValue: 224
        description: "Latin small letter A with grave"
        replacement: "a"
      - charValue: 225
        description: "Latin small letter A with acute"
        replacement: "a"
      - charValue: 226
        description: "Latin small letter A with circumflex"
        replacement: "a"
      - charValue: 228
        description: "Latin small letter A with dieresis"
        replacement: "a"
      - charValue: 232
        description: "Latin small letter E with grave"
        replacement: "e"
      - charValue: 233
        description: "Latin small letter E with acute"
        replacement: "e"
      - charValue: 234
        description: "Latin small letter E with circumflex"
        replacement: "e"
      - charValue: 235
        description: "Latin small letter E with dieresis"
        replacement: "e"
      - charValue: 236
        description: "Latin small letter I with grave"
        replacement: "i"
      - charValue: 237
        description: "Latin small letter I with acute"
        replacement: "i"
      - charValue: 238
        description: "Latin small letter I with circumflex"
        replacement: "i"
      - charValue: 239
        description: "Latin small letter I with dieresis"
        replacement: "i"
      - charValue: 242
        description: "Latin small letter O with grave"
        replacement: "o"
      - charValue: 243
        description: "Latin small letter O with acute"
        replacement: "o"
      - charValue: 244
        description: "Latin small letter O with circumflex"
        replacement: "o"
      - charValue: 246
        description: "Latin small letter O with dieresis"
        replacement: "o"
      - charValue: 249
        description: "Latin small letter U with grave"
        replacement: "u"
      - charValue: 250
        description: "Latin small letter U with acute"
        replacement: "u"
      - charValue: 251
        description: "Latin small letter U with circumflex"
        replacement: "u"
      - charValue: 252
        description: "Latin small letter U with dieresis"
        replacement: "u"
      - charValue: 7809
        description: "Latin small letter W with grave"
        replacement: "w"
      - charValue: 7811
        description: "Latin small letter W with acute"
        replacement: "w"
      - charValue: 373
        description: "Latin small letter W with circumflex"
        replacement: "w"
      - charValue: 7813
        description: "Latin small letter W with dieresis"
        replacement: "w"
      - charValue: 7923
        description: "Latin small letter Y with grave"
        replacement: "y"
      - charValue: 253
        description: "Latin small letter Y with acute"
        replacement: "y"
      - charValue: 375
        description: "Latin small letter Y with circumflex"
        replacement: "y"
      - charValue: 255
        description: "Latin small letter Y with dieresis"
        replacement: "y"
