version: '2.1'

services:
  civil-rtl-export:
    build:
      context: .
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: hmcts/civil-rtl-export
    environment:
      # these environment variables are used by java-logging library
      - ROOT_APPENDER
      - JSON_CONSOLE_PRETTY_PRINT
      - ROOT_LOGGING_LEVEL
      - REFORM_SERVICE_TYPE
      - REFORM_SERVICE_NAME
      - REFORM_TEAM
      - REFORM_ENVIRONMENT
      - LOGBACK_DATE_FORMAT
      - LOGBACK_REQUIRE_THREAD
      - LOGBACK_REQUIRE_ALERT_LEVEL=false
      - LOGBACK_REQUIRE_ERROR_CODE=false
    ports:
      - $SERVER_PORT:$SERVER_PORT
    depends_on:
      - civil-rtl-export-database
    links:
      - civil-rtl-export-database

  civil-rtl-export-database:
    build:
      context: docker/database
    image: hmcts/civil-rtl-export-database
    healthcheck:
      interval: 10s
      timeout: 10s
      retries: 10
    environment:
      - JF_DB_USERNAME=jf_user
      - JF_DB_PASSWORD=jf_pass
    ports:
      - 5455:5432
    volumes:
      - civil-rtl-export-database-data:/var/lib/postgresql/data

volumes:
  civil-rtl-export-database-data:
