spring:
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:postgresql:15:///civil-rtl-export-db?stringtype=unspecified
  test:
    database:
      replace: none

rtl-export:
  task:
    scheduledReport:
      asOf: null
      test: false
      serviceId: null
    housekeeping:
      minimumAge: 90
  sftp:
    host: localhost
    serverPort: 1024
    remoteDir: data
