spring:
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:postgresql:15:///civil_rtl_export_db?stringtype=unspecified
  test:
    database:
      replace: none

rtl-export:
  task:
    scheduledReport:
      asOf: null
      test: false
      serviceId: null
    housekeeping:
      minimumAge: 90
  sftp:
    host: localhost
    serverPort: 1024
    remoteDir: data
  validate:
    service-ids[0]: "IT01"
    service-ids[1]: "IT02"
  replace:
    character-replacements:
      - charValue: 207
        description: "Latin capital letter I with dieresis"
        replacement: "I"
      - charValue: 212
        description: "Latin capital letter O with circumflex"
        replacement: "O"
      - charValue: 189
        description: "Vulgar fraction one half"
        replacement: ".5"
