java:
  applicationPort: 4550
  image: 'hmctspublic.azurecr.io/civil/rtl-export:latest'
  ingressHost: civil-rtl-export-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
  aadIdentityName: civil
  keyVaults:
    civil-rtl-export:
      secrets:
        - name: civil-rtl-export-appinsights-connection-string
          alias: APPINSIGHTS_CONNECTION_STRING
  environment:
