java:
  applicationPort: 4550
  image: 'hmctspublic.azurecr.io/civil/rtl-export:latest'
  ingressHost: civil-rtl-export-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
  aadIdentityName: civil
  environment:
    JF_DB_NAME: civil_rtl_export
    JF_DB_PORT: 5432
  keyVaults:
    civil-rtl-export:
      secrets:
        - name: civil-rtl-export-appinsights-connection-string
          alias: APPINSIGHTS_CONNECTION_STRING
        - name: civil-rtl-export-POSTGRES-USER-V15
          alias: JF_DB_USERNAME
        - name: civil-rtl-export-POSTGRES-PASS-V15
          alias: JF_DB_PASSWORD
        - name: civil-rtl-export-POSTGRES-HOST-V15
          alias: JF_DB_HOST
        - name: sftp-host
          alias: SFTP_HOST
        - name: sftp-port
          alias: SFTP_PORT
        - name: sftp-username
          alias: SFTP_USERNAME
        - name: sftp-password
          alias: SFTP_PASSWORD
